### ISSUE TITLE
TODO #1

### ISSUE THREAD

**Issue by mkozachok** [Oleksandr511/react-shopping-list#1]
https://github.com/Oleksandr511/react-shopping-list/blob/8419543bf7de1bcc14696b9d676e685e3aa9b4a1/src/App.js#L21

- [ ] Create new branch with name  - `task-1` and continue work in this branch.
- [ ] Split code into components. Create `ProductListItem` component and locate in `./src/components/ListItem`.
- [ ] Create `ProductList` component and locate in `./src/components/ProductList`.
- [ ] Create `ProductList` component and locate in `./src/components/NewProduct`.
- [ ] Create hook `useProductList` in `./src/components/ProductList`. Move useState and all logic into it. 

start from this 
```javascript
const [products, setProducts] = useState([
{label: 'tomatos', done: false},
// etc
])
```

- [ ] Create pull request from `task-1` to `main` when work will be done.

**Comment by mkozachok** [comment]
@Oleksandr511 Please check
![image](https://github.com/Oleksandr511/react-shopping-list/assets/10548300/876236d3-ad58-4bc0-96fe-d8908edfb9bc)
